on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build:
    name: Pull Request Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
          scope: justinm
      - run: npm install
      - run: npm run lint
      - name: Release
        run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: github.ref != 'refs/heads/main'
