on:
  push:
    branches:
      - main
  workflow_dispatch: {}
concurrency: 1
jobs:
  release:
    name: Release Workflow
    runs-on: ubuntu-latest
    environment: master
    permissions:
      contents: write
    outputs:
      latest_commit: ${{ steps.check.outputs.latest_commit }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
          scope: justinm
      - run: yarn config set --home npmAuthToken ${{ secrets.NPM_TOKEN }}
      - run: yarn
      - name: Release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        id: Release
      - name: Check for new commits
        run: echo ::set-output name=latest_commit::"$(git ls-remote origin -h ${{ github.ref }} | cut -f1)"
        id: check
